import type {
  Causa,
  DonacionExtendida,
  TopDonador,
  User,
  Voluntario,
  CentroAcopio,
  EvidenciaCampana,
  ImpactoRegion,
  Partner,
  ChartDataMonth,
} from '../types'

export const mockCausas: Causa[] = [
  {
    id: 1,
    titulo: 'Reconstrucción Escuela Rural Putaendo',
    descripcion:
      'Ayuda a reconstruir la escuela primaria de Putaendo afectada por las lluvias de invierno. Más de 200 niños esperan volver a clases.',
    imagen: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600&auto=format',
    meta: 15000000,
    recaudado: 9750000,
    categoria: 'Educación',
    activa: true,
    fechaFin: '2026-07-31',
  },
  {
    id: 2,
    titulo: 'Alimentación para Adultos Mayores Valparaíso',
    descripcion:
      'Programa de cajas de alimentos mensuales para 150 adultos mayores en situación de vulnerabilidad en el Gran Valparaíso.',
    imagen: 'https://images.unsplash.com/photo-1593113616828-6f22bca04804?w=600&auto=format',
    meta: 8000000,
    recaudado: 6200000,
    categoria: 'Alimentación',
    activa: true,
    fechaFin: '2026-08-15',
  },
  {
    id: 3,
    titulo: 'Medicamentos Oncológicos Niños La Serena',
    descripcion:
      'Financiamiento de tratamientos oncológicos para 12 niños del Hospital de La Serena que no cuentan con cobertura FONASA completa.',
    imagen: 'https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?w=600&auto=format',
    meta: 25000000,
    recaudado: 7500000,
    categoria: 'Salud',
    activa: true,
    fechaFin: '2026-09-30',
  },
  {
    id: 4,
    titulo: 'Refugio Animales Santiago Sur',
    descripcion:
      'Ampliación del refugio municipal de animales en Santiago Sur para albergar a 80 perros y gatos rescatados de la calle.',
    imagen: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&auto=format',
    meta: 6000000,
    recaudado: 5800000,
    categoria: 'Animales',
    activa: false,
    fechaFin: '2026-04-30',
  },
]

export const mockDonaciones: DonacionExtendida[] = [
  {
    id: 1,
    donadorNombre: 'María González',
    donadorEmail: 'maria@email.com',
    monto: 50000,
    causaId: 1,
    causaTitulo: 'Reconstrucción Escuela Rural Putaendo',
    fecha: '2026-05-01T10:30:00Z',
    mensaje: '¡Adelante! Los niños merecen una buena educación.',
    anonima: false,
    estado: 'completada',
    tipo: 'monetaria',
    destino: 'Centro Putaendo Norte',
  },
  {
    id: 2,
    donadorNombre: 'Carlos Rodríguez',
    donadorEmail: 'carlos@email.com',
    monto: 100000,
    causaId: 2,
    causaTitulo: 'Alimentación para Adultos Mayores Valparaíso',
    fecha: '2026-05-02T14:15:00Z',
    mensaje: '',
    anonima: false,
    estado: 'en_proceso',
    tipo: 'alimento',
    destino: 'Centro Valparaíso Centro',
  },
  {
    id: 3,
    donadorNombre: 'Anónimo',
    monto: 200000,
    causaId: 3,
    causaTitulo: 'Medicamentos Oncológicos Niños La Serena',
    fecha: '2026-05-03T09:00:00Z',
    mensaje: 'Con todo el corazón.',
    anonima: true,
    estado: 'completada',
    tipo: 'medica',
    destino: 'Hospital La Serena',
  },
  {
    id: 4,
    donadorNombre: 'Ana Martínez',
    donadorEmail: 'ana@email.com',
    monto: 75000,
    causaId: 1,
    causaTitulo: 'Reconstrucción Escuela Rural Putaendo',
    fecha: '2026-05-04T16:45:00Z',
    mensaje: '',
    anonima: false,
    estado: 'pendiente',
    tipo: 'monetaria',
    destino: 'Centro Putaendo Norte',
  },
  {
    id: 5,
    donadorNombre: 'Roberto Silva',
    donadorEmail: 'roberto@email.com',
    monto: 30000,
    causaId: 2,
    causaTitulo: 'Alimentación para Adultos Mayores Valparaíso',
    fecha: '2026-05-05T11:20:00Z',
    mensaje: 'Un pequeño aporte para una gran causa.',
    anonima: false,
    estado: 'pendiente',
    tipo: 'alimento',
    destino: 'Centro Valparaíso Centro',
  },
  {
    id: 6,
    donadorNombre: 'Valentina Torres',
    donadorEmail: 'vale@email.com',
    monto: 150000,
    causaId: 3,
    causaTitulo: 'Medicamentos Oncológicos Niños La Serena',
    fecha: '2026-05-06T08:00:00Z',
    mensaje: '',
    anonima: false,
    estado: 'en_proceso',
    tipo: 'medica',
    destino: 'Hospital La Serena',
  },
  {
    id: 7,
    donadorNombre: 'Felipe Muñoz',
    donadorEmail: 'felipe@email.com',
    monto: 45000,
    causaId: 1,
    causaTitulo: 'Reconstrucción Escuela Rural Putaendo',
    fecha: '2026-05-07T13:10:00Z',
    mensaje: 'Fuerza Putaendo!',
    anonima: false,
    estado: 'completada',
    tipo: 'ropa',
    destino: 'Centro Santiago Poniente',
  },
  {
    id: 8,
    donadorNombre: 'Catalina Vega',
    donadorEmail: 'catalina@email.com',
    monto: 80000,
    causaId: 2,
    causaTitulo: 'Alimentación para Adultos Mayores Valparaíso',
    fecha: '2026-04-20T10:00:00Z',
    mensaje: '',
    anonima: false,
    estado: 'completada',
    tipo: 'alimento',
    destino: 'Centro Viña del Mar',
  },
  {
    id: 9,
    donadorNombre: 'Diego Araya',
    donadorEmail: 'diego@email.com',
    monto: 25000,
    causaId: 3,
    causaTitulo: 'Medicamentos Oncológicos Niños La Serena',
    fecha: '2026-04-15T15:30:00Z',
    mensaje: 'Fuerza pequeños guerreros.',
    anonima: false,
    estado: 'cancelada',
    tipo: 'monetaria',
    destino: 'Hospital La Serena',
  },
  {
    id: 10,
    donadorNombre: 'Laura Espinoza',
    donadorEmail: 'laura@email.com',
    monto: 60000,
    causaId: 1,
    causaTitulo: 'Reconstrucción Escuela Rural Putaendo',
    fecha: '2026-04-10T09:15:00Z',
    mensaje: '',
    anonima: false,
    estado: 'completada',
    tipo: 'monetaria',
    destino: 'Centro Putaendo Norte',
  },
]

export const mockTopDonadores: TopDonador[] = [
  { id: 1, nombre: 'Valentina Torres', totalDonado: 450000, cantidadDonaciones: 8 },
  { id: 2, nombre: 'Carlos Rodríguez', totalDonado: 380000, cantidadDonaciones: 5 },
  { id: 3, nombre: 'María González', totalDonado: 275000, cantidadDonaciones: 7 },
  { id: 4, nombre: 'Ana Martínez', totalDonado: 210000, cantidadDonaciones: 4 },
  { id: 5, nombre: 'Roberto Silva', totalDonado: 185000, cantidadDonaciones: 6 },
]

export const mockUsers: User[] = [
  {
    id: 1,
    nombre: 'Admin Donaton',
    email: 'admin@donaton.cl',
    rol: 'admin',
    fechaRegistro: '2025-01-10',
    totalDonaciones: 0,
  },
  {
    id: 2,
    nombre: 'María González',
    email: 'maria@email.com',
    rol: 'donador',
    fechaRegistro: '2025-03-15',
    totalDonaciones: 7,
  },
  {
    id: 3,
    nombre: 'Carlos Rodríguez',
    email: 'carlos@email.com',
    rol: 'donador',
    fechaRegistro: '2025-04-20',
    totalDonaciones: 5,
  },
  {
    id: 4,
    nombre: 'Valentina Torres',
    email: 'vale@email.com',
    rol: 'donador',
    fechaRegistro: '2025-02-08',
    totalDonaciones: 8,
  },
  {
    id: 5,
    nombre: 'Roberto Silva',
    email: 'roberto@email.com',
    rol: 'donador',
    fechaRegistro: '2025-05-01',
    totalDonaciones: 6,
  },
]

export const mockCentrosAcopio: CentroAcopio[] = [
  {
    id: 1,
    nombre: 'Centro Santiago Poniente',
    direccion: 'Av. Libertador B. OHiggins 1234',
    region: 'Metropolitana',
    ciudad: 'Santiago',
    horario: 'Lun-Vie 9:00-18:00, Sáb 10:00-14:00',
    telefono: '+56 2 2345 1001',
    queRecibe: ['Ropa de abrigo', 'Frazadas', 'Calzado', 'Alimentos no perecibles'],
    capacidadActual: 340,
    capacidadMax: 500,
    activo: true,
    coordenadas: { lat: -33.4489, lng: -70.6693 },
  },
  {
    id: 2,
    nombre: 'Centro Santiago Norte',
    direccion: 'Av. Independencia 567, Recoleta',
    region: 'Metropolitana',
    ciudad: 'Santiago',
    horario: 'Lun-Vie 8:00-17:00',
    telefono: '+56 2 2345 1002',
    queRecibe: ['Ropa de abrigo', 'Medicamentos', 'Útiles escolares'],
    capacidadActual: 210,
    capacidadMax: 400,
    activo: true,
    coordenadas: { lat: -33.4183, lng: -70.6508 },
  },
  {
    id: 3,
    nombre: 'Centro Santiago Sur',
    direccion: 'Gran Avenida 890, San Miguel',
    region: 'Metropolitana',
    ciudad: 'Santiago',
    horario: 'Mar-Sáb 9:00-17:00',
    telefono: '+56 2 2345 1003',
    queRecibe: ['Frazadas', 'Calzado', 'Alimentos no perecibles'],
    capacidadActual: 180,
    capacidadMax: 300,
    activo: true,
    coordenadas: { lat: -33.5000, lng: -70.6500 },
  },
  {
    id: 4,
    nombre: 'Centro Providencia',
    direccion: 'Av. Providencia 1500',
    region: 'Metropolitana',
    ciudad: 'Santiago',
    horario: 'Lun-Vie 10:00-19:00, Sáb 10:00-14:00',
    telefono: '+56 2 2345 1004',
    queRecibe: ['Ropa de abrigo', 'Frazadas', 'Juguetes'],
    capacidadActual: 290,
    capacidadMax: 350,
    activo: true,
    coordenadas: { lat: -33.4372, lng: -70.6196 },
  },
  {
    id: 5,
    nombre: 'Centro Maipú',
    direccion: 'Av. 5 de Abril 430, Maipú',
    region: 'Metropolitana',
    ciudad: 'Santiago',
    horario: 'Lun-Sáb 9:00-18:00',
    telefono: '+56 2 2345 1005',
    queRecibe: ['Ropa de abrigo', 'Calzado', 'Alimentos no perecibles', 'Frazadas'],
    capacidadActual: 420,
    capacidadMax: 600,
    activo: true,
    coordenadas: { lat: -33.5123, lng: -70.7601 },
  },
  {
    id: 6,
    nombre: 'Centro Valparaíso Centro',
    direccion: 'Av. Brasil 678, Valparaíso',
    region: 'Valparaíso',
    ciudad: 'Valparaíso',
    horario: 'Lun-Vie 9:00-18:00',
    telefono: '+56 32 234 5006',
    queRecibe: ['Ropa de abrigo', 'Frazadas', 'Alimentos no perecibles'],
    capacidadActual: 150,
    capacidadMax: 280,
    activo: true,
    coordenadas: { lat: -33.0472, lng: -71.6127 },
  },
  {
    id: 7,
    nombre: 'Centro Viña del Mar',
    direccion: 'Av. Marina 890, Viña del Mar',
    region: 'Valparaíso',
    ciudad: 'Viña del Mar',
    horario: 'Mar-Sáb 10:00-17:00',
    telefono: '+56 32 234 5007',
    queRecibe: ['Ropa de abrigo', 'Calzado', 'Útiles escolares'],
    capacidadActual: 95,
    capacidadMax: 200,
    activo: true,
    coordenadas: { lat: -33.0245, lng: -71.5518 },
  },
  {
    id: 8,
    nombre: 'Centro Concepción Biobío',
    direccion: 'Av. Los Carrera 234, Concepción',
    region: 'Biobío',
    ciudad: 'Concepción',
    horario: 'Lun-Vie 8:30-17:30',
    telefono: '+56 41 234 5008',
    queRecibe: ['Ropa de abrigo', 'Frazadas', 'Alimentos no perecibles', 'Medicamentos'],
    capacidadActual: 310,
    capacidadMax: 450,
    activo: true,
    coordenadas: { lat: -36.8201, lng: -73.0444 },
  },
  {
    id: 9,
    nombre: 'Centro Talcahuano',
    direccion: 'Av. Colón 567, Talcahuano',
    region: 'Biobío',
    ciudad: 'Talcahuano',
    horario: 'Lun-Sáb 9:00-16:00',
    telefono: '+56 41 234 5009',
    queRecibe: ['Ropa de abrigo', 'Calzado', 'Frazadas'],
    capacidadActual: 140,
    capacidadMax: 250,
    activo: false,
    coordenadas: { lat: -36.7246, lng: -73.1171 },
  },
]

export const mockEvidencias: EvidenciaCampana[] = [
  {
    id: 1,
    titulo: 'Campaña Poleras Invierno 2024',
    fecha: '2024-07-15',
    monto: 10200000,
    beneficiarios: 847,
    descripcion: '847 poleras de abrigo entregadas a familias en situación de vulnerabilidad en la Región Metropolitana y Valparaíso.',
    detalle: [
      '847 poleras de abrigo talla S-XXL entregadas',
      '$10.200.000 pesos gestionados',
      'Coordinación con 4 centros de acopio activos',
      'Verificación fotográfica de cada entrega',
      '3 semanas de distribución activa',
    ],
    centrosBeneficiados: ['Centro Santiago Poniente', 'Centro Santiago Norte', 'Centro Valparaíso Centro', 'Centro Maipú'],
    tipo: 'ropa',
  },
  {
    id: 2,
    titulo: 'Alimentación Mayo 2024',
    fecha: '2024-05-30',
    monto: 4500000,
    beneficiarios: 150,
    descripcion: '150 familias recibieron cajas de alimentos durante el mes de mayo, con un total de 2.300 kg de alimentos distribuidos.',
    detalle: [
      '150 cajas de alimentos entregadas',
      '2.300 kg de alimentos no perecibles distribuidos',
      '$4.500.000 pesos invertidos en alimentos',
      'Alianza con Banco de Alimentos Chile',
      'Cobertura en 3 comunas de Santiago',
    ],
    centrosBeneficiados: ['Centro Santiago Sur', 'Centro Providencia'],
    tipo: 'alimento',
  },
  {
    id: 3,
    titulo: 'Medicamentos Invierno 2024',
    fecha: '2024-06-20',
    monto: 6800000,
    beneficiarios: 45,
    descripcion: 'Provisión de medicamentos para 45 pacientes de escasos recursos en tratamiento oncológico.',
    detalle: [
      '45 pacientes beneficiados directamente',
      '$6.800.000 en medicamentos gestionados',
      'Coordinación con Hospital Regional La Serena',
      'Seguimiento mensual de cada paciente',
    ],
    centrosBeneficiados: ['Hospital La Serena'],
    tipo: 'medicamento',
  },
]

export const mockImpactoRegion: ImpactoRegion[] = [
  { id: 1, nombre: 'Metropolitana', codigo: 'RM', familiasAyudadas: 1420, kilosRopa: 8540, centrosActivos: 5, nivel: 5 },
  { id: 2, nombre: 'Valparaíso', codigo: 'V', familiasAyudadas: 380, kilosRopa: 2100, centrosActivos: 2, nivel: 3 },
  { id: 3, nombre: 'Biobío', codigo: 'VIII', familiasAyudadas: 290, kilosRopa: 1680, centrosActivos: 2, nivel: 3 },
  { id: 4, nombre: 'Araucanía', codigo: 'IX', familiasAyudadas: 180, kilosRopa: 940, centrosActivos: 1, nivel: 2 },
  { id: 5, nombre: 'Maule', codigo: 'VII', familiasAyudadas: 145, kilosRopa: 720, centrosActivos: 1, nivel: 2 },
  { id: 6, nombre: 'Coquimbo', codigo: 'IV', familiasAyudadas: 95, kilosRopa: 450, centrosActivos: 1, nivel: 1 },
  { id: 7, nombre: 'O\'Higgins', codigo: 'VI', familiasAyudadas: 75, kilosRopa: 380, centrosActivos: 0, nivel: 1 },
]

export const mockPartners: Partner[] = [
  { id: 1, nombre: 'Falabella', tipo: 'empresa', descripcion: 'Donaciones de ropa y logística', iniciales: 'FA', color: 'bg-green-600' },
  { id: 2, nombre: 'Sodimac', tipo: 'empresa', descripcion: 'Materiales de construcción y ferretería', iniciales: 'SO', color: 'bg-orange-600' },
  { id: 3, nombre: 'Cruz Roja Chile', tipo: 'ong', descripcion: 'Coordinación de voluntarios y medicamentos', iniciales: 'CR', color: 'bg-red-600' },
  { id: 4, nombre: 'TECHO Chile', tipo: 'ong', descripcion: 'Construcción de viviendas de emergencia', iniciales: 'TC', color: 'bg-yellow-600' },
  { id: 5, nombre: 'Un Techo para Chile', tipo: 'ong', descripcion: 'Programas de vivienda social', iniciales: 'UT', color: 'bg-blue-600' },
  { id: 6, nombre: 'BancoEstado', tipo: 'empresa', descripcion: 'Gestión de transferencias y pagos', iniciales: 'BE', color: 'bg-purple-600' },
]

export const mockChartData: ChartDataMonth[] = [
  { mes: 'Ene', total: 980000, monetario: 720000, especie: 260000 },
  { mes: 'Feb', total: 1240000, monetario: 890000, especie: 350000 },
  { mes: 'Mar', total: 1580000, monetario: 1100000, especie: 480000 },
  { mes: 'Abr', total: 2100000, monetario: 1500000, especie: 600000 },
  { mes: 'May', total: 1870000, monetario: 1320000, especie: 550000 },
  { mes: 'Jun', total: 2340000, monetario: 1680000, especie: 660000 },
  { mes: 'Jul', total: 3100000, monetario: 2200000, especie: 900000 },
  { mes: 'Ago', total: 2750000, monetario: 1950000, especie: 800000 },
  { mes: 'Sep', total: 2050000, monetario: 1450000, especie: 600000 },
  { mes: 'Oct', total: 1920000, monetario: 1380000, especie: 540000 },
  { mes: 'Nov', total: 2280000, monetario: 1620000, especie: 660000 },
  { mes: 'Dic', total: 3450000, monetario: 2500000, especie: 950000 },
]
